name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy. This should be the Git SHA of the commit that was built.'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/psfss-frontend/psfss-frontend:${{ steps.vars.outputs.sha_short }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}

  request_deployment:
    name: Request Deployment
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Create a deployment request
        run: echo "A new image has been built. To deploy, run the workflow manually with the tag '${{ needs.build.outputs.image_tag }}'."

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: production
    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MANIFEST_REPO }} # e.g., 'your-org/k8s-manifests'
          token: ${{ secrets.MANIFEST_REPO_PAT }} # A PAT with repo write access

      - name: Update image tag in manifest
        run: |
          # This example uses sed to update the image tag in a Kubernetes manifest.
          # You may need to adjust this depending on your manifest structure (e.g., using kustomize, helm, etc.)
          sed -i' "s|image: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/psfss-frontend/psfss-frontend:.*|image: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/psfss-frontend/psfss-frontend:${{ github.event.inputs.image_tag }}|g" path/to/your/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Deploy image ${{ github.event.inputs.image_tag }} for psfss-frontend"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MANIFEST_REPO_PAT }}
